sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
cache:
  directories:
  - vendor
  - "$HOME/.composer/cache"
matrix:
  include:
  - php: 7.1
    env: WP_VERSION=latest
  - php: 7.1
    env: WP_VERSION=trunk
  - php: 7.0
    env: WP_VERSION=latest
  - php: 7.0
    env: WP_VERSION=trunk
  - php: 5.6
    env: WP_VERSION=latest
  - php: 5.6
    env: WP_VERSION=trunk
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- composer install --no-dev
script:
- phpunit
- WP_MULTISITE=1 phpunit
after_success:
- sed -i -e "s/nightly/${TRAVIS_TAG}/" $(basename $TRAVIS_REPO_SLUG).php
- curl https://raw.githubusercontent.com/miya0001/auto-build/master/auto-build.sh
  | bash
deploy:
  provider: releases
  api_key:
    secure: axarBP9+cbS2/tEYvdkeR3fPPLMeZ1px5IdgmEpqXRkRfHPxos7YtnGZ27FVliM3dNtXMxL2I9F0KklC3Ru1VzrYnwMYnImiHrBqocO5xJIwlWPwgj1X9sBtk2i8Kw3eoCRXP0teN14US4dbdMakjw+DeGql2q6mF3s04la7MfXY0orxbhwLvzHn0yfdWHEo20QyuUeAJsS6QyJygeIWmHIpd86baPvJwzdkQj4StDfiW74CXRiaaZ1Mtrsp0un+9exrY60E/NJC77+aOW6GGQWu8KMt24ozqqqaFOTiHMwQnG+8RMi7AtGnj3cknUESCgeGnimAGvibxFta6o2iCARFPt6UDLSNyuDBlaSV2BkXQqCMTKlXepW72fLAzkc7izCRSI+FhlcxaJTCflMDQSM74/e2Gg3SdRcijjAuqJokom2CHmQ8R2Z9QaZXRoP2hcj4uUnbo8lfRNX9hKcIuB1pbddqhVZ0Jdn7PXTNxX9pf7Jc29A5C3ftxOnYOd4tke2phiMUWXcZWV5APQ96TEsVFzw1ix/YmloQ/xZ+M8Ketf5q9Aauo6mrTF7QxEWUaWM2zQ+JTlXqxn1rT5pTJFcYyeBjApbHssE87w+RLeLGVFXyQW27Fun2NZR1Nn0436PZOLvv97DU68Ys3p0zU0PY+lLCyiEzaqG+d4/PUiE=
  file: logbook.zip
  on:
    tags: true
    repo: tarosky/logbook
